vcs:
  type: git
agents:
  available:
  - claude
  - opencode
  - codex
  auto_commit: true
project:
  uuid: bebf8d60-7c5d-4459-94b6-e0f3e4ad83f9
  slug: spec-kitty-events
  node_id: d036a097a835
  build_id: 9324aef4-7e11-420a-8c53-46e88baa534f
charter: .kittify/charter/charter.yaml
